# theme params
defaultTheme: light
# disableThemeToggle: true
favicon: favicon.png
appleTouchIcon: favicon.png

# param for home/archive listing
mainSections: posts # section to search posts from

# theme setting per post
comments: true
math: true # math mode on by default
editPost:
  URL: "https://github.com/allen-liaoo/alsblog/tree/HEAD/content"
  Text: "View Source" # edit text
  appendFilePath: true # to append file path to Edit link
TocSide: left
showToc: true
TocOpen: true
ShowBreadCrumbs: false
ShowReadingTime: false
ShowCodeCopyButtons: true # for each codeblock

# EnableInstantClick: true

# fuse.js search options
fuseOpts:
  shouldSort: true
  includeMatches: true
  threshold: 0.4 # fuzzy match
  ignoreLocation: true # search anywhere in below sections
  keys: ["title", "permalink", "summary", "content"]

assets:
  disableHLJS: true # disable papermod's highlight.js

socialIcons: # optional for home page mode (not on)
  - name: "Github"
    url: "https://github.com/allen-liaoo/"
  - name: "email"
    url: "mailto://wcliaw610@gmail.com"